# Generated by Django 3.2.8 on 2021-10-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogos', '0004_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario', serialize=False, to='auth.user', verbose_name='Usuario')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to='catalogos.fotos')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidad', to='catalogos.pais', verbose_name='Nacionalidad')),
            ],
        ),
    ]
